config/routes.rb
Rails.application.routes.draw do
  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 
  'registrations' }

  resources :users do
  	resources :tweets
    resources :scoreboards
  end


  resources :homes
  root "users#index"

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	# has_many :authorizations, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable
  has_many :identities
  has_many :tweets
  has_many :scoreboards

  def twitter
    identities.where( :provider => "twitter" ).first
  end

  def twitter_client
    @twitter_client ||= Twitter.client( access_token: twitter.accesstoken )
  end

  def facebook
    identities.where( :provider => "facebook" ).first
  end

  def facebook_client
    @facebook_client ||= Facebook.client( access_token: facebook.accesstoken )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		
		if user_signed_in?
			@id = current_user.id
			@identity = Identity.where(user_id: @id).first

			# TweetStream::Client.new.sample do |status|
 		# 		puts "#{status.text}"
			# end
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_navbar.html.erb
<% if user_signed_in? %>	
<!-- 	<strong>  	 -->	
		<!-- <li class="notice"><%= notice %></li>
        <li class="lead alert"><%= alert %></li> -->
	 	<% @id = Identity.find_by(:user_id => current_user.id)%>
		<% if @id.name? %>
			<li> <%= @id.name %> </li>
			<li class="img-thumbnail"><%= image_tag("#{@id.image}") %> </li>
		<% else %>
			<li> <%= @id.email %> </li>
			<li> <%= image_tag("#{@id.image}") %> </li>
		<% end %>
	<!-- </strong>	 -->
		<button type="button" class="btn btn-primary"><%=link_to '<span class="glyphicon glyphicon-home"></span>'.html_safe, users_path%> </button>
		<button type="button" class="btn btn-primary"><%=link_to '<span class="glyphicon glyphicon-user"></span>'.html_safe, edit_user_registration_path %></button>
		<button type="button" class="btn btn-danger"><%=link_to '<span class="glyphicon glyphicon-off"></span>'.html_safe, destroy_user_session_path, method: :delete %></button>
		<button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#about">
  		<span class="glyphicon glyphicon-question-sign"></span>
		</button>  
<%else%>
		
<%end%>  

app/views/users/index.html.erb
<div class="inner cover">
   	   	
</div>

<% if !user_signed_in? %>
<div>
<%= image_tag("live-long-and-prosper.jpg", :class => "home_page_image") %>
</div>
<div>
    <button type="button" id="spock_button" class="btn btn-primary" data-toggle="modal" data-target="#signIn">Come Back Mr. Spock</button>
</div>

<% end %>

<div id="container-chart">
</div>

<!-- Modal -->
<div class="modal fade" id="about" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">What is Twitter Vibe?</h4>

      </div>
      <div class="modal-body">
        <p>Twitter Vibe is a Twitter sentiment analysis application that assigns a positive / negative score to your tweets with a lexicon library called AFINN.  </p>
        <br>
        <p> The results are graphed on an area chart with a line graph representing the average score for the given day </p>
        <br>
        <p>The green area shows the range of your most positive tweets while the red shows the range of your most negative tweets.</p> 
        <br>
        <p> The blue line that contained within the two shaded areas is the average score of all your tweets in a given day. </p>


      </div>
      <div class="modal-footer">
        <% if !user_signed_in? %>
        <button type="button" id="twitter_sign_in" class="btn btn-success"><%= link_to "Tweet me up Scotty!", user_omniauth_authorize_path(:twitter)%></button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Meh, ok</button>
        <%else%>
            <button type="button" class="btn btn-success" data-dismiss="modal"> Got it Captain Kirk </button>
        <%end%>
      </div>
    </div>
  </div>
</div>
<!-- End of Modal -->

<% if user_signed_in? %>
	<div id="range_nav">
		<form>
			Start Date
			<input type="date" id="start_date">
			End Date
			<input type="date" id="end_date">
			<button id="range" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span></button>
			<%= button_to 'Analyze Older Tweets', new_user_tweet_path(:user_id => @id), :method => :get, class: "btn btn-primary" %>
		</form>
	</div>
<%end%>
<!-- Oembeded Timeline
 --><!-- <a class="twitter-timeline" 
href="https://twitter.com/Quant_LIfe" 
data-widget-id="571770754627555328"
>Tweets by @Quant_LIfe</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.creaidentiteElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>-->
<!-- End of Oembeded Timeline
 -->
<div class="mastfoot">
	<div class="inner">
  		<p> Twitter Vibe by Sung Kim </p>
	</div>  	
</div>



<script>
//Makes AJAX call for User Tweets
function userTweets(userId) {


	var points_url = window.location.origin + "/users/" + userId + "/scoreboards.json";

	$.ajax({
		type: "GET",
		url: points_url,
		dataType: "json",
		success: function(points){
			graphTweets(points);

		},
		error: function(){
			alert('AJAX call for Points has failed');
		}
	});
};

	var ranges = [];
	var averages = []; 

function graphTweets(points){

	_.each(points, function(point, i){
		var	datetime = parseInt(point["datetime"], 10);
		var minscore = parseInt(point["minscore"], 10);
		var maxscore = parseInt(point["maxscore"], 10);
		var avgscore = parseInt(point["avgscore"], 10);
		var newrange = []
		var newaverage = []
		newrange.push(datetime, minscore, maxscore)
		newaverage.push(datetime, avgscore)
		ranges.push(newrange)
		averages.push(newaverage)	
	})

    $('#container-chart').highcharts({
        title: {
            text: 'Your Tweet Vibes'
        },

        chart: {
        	borderRadius: 20,
        	// plotBackgroundColor: "#BAB3B2"
        },

        credits: {
        	enabled: false
        },

        xAxis: {
            type: 'datetime'
        },

        yAxis: {
            title: {
                text: 'Sentiment'
            }
        },

        tooltip: {
            crosshairs: true,
            shared: true,
            valueSuffix: ''
        },

        series: [{
            name: 'Average',
            data: averages,
            zIndex: 1,
            marker: {
                fillColor: 'white',
                lineWidth: 2,
                lineColor: Highcharts.getOptions().colors[0]
            }
        }, {
            name: 'Range',
            data: ranges,
            type: 'arearange',
            color: "#66CD00",
            negativeColor: "#FF0000",
            lineWidth: 0,
            linkedTo: ':previous',
            fillOpacity: 0.3,
            zIndex: 0
        }]
    });
}

<% if user_signed_in? %>
userTweets(<%=current_user.id%>);
<% end %>

//Listener for Range Button
$('#range').click(function(event){
	event.preventDefault();

	<% if user_signed_in? %>
	var userId = <%=current_user.id%>
	<% end %>

	var points_url = window.location.origin + "/users/" + userId + "/scoreboards.json";

	$.ajax({
		type: "GET",
		url: points_url,
		dataType: "json",
		success: function(points){
			graphFilteredTweets(points);

		},
		error: function(){
			alert('AJAX call for Points has failed');
		}
	});
})

 
function graphFilteredTweets(points){
	var ranges = [];
	var averages = [];
	var startDate = $('#start_date').val().split("-");
	var endDate = $('#end_date').val().split("-");
	var sMonth= startDate[1];
	var sDay= startDate[2];
	var sYear = startDate[0];
	var eMonth = endDate[1];
	var eYear = endDate[0];
	var eDay= endDate[2];
	var sCombined = sYear+sMonth+sDay;
	var eCombined = eYear+eMonth+eDay;

	var formattedStartDate = parseInt(sCombined);
	var formattedEndDate = parseInt(eCombined);
	
	_.each(points, function(point, i){
        var datetime = parseInt(point["datetime"], 10);
        var minscore = parseInt(point["minscore"], 10);
        var maxscore = parseInt(point["maxscore"], 10);
        var avgscore = parseInt(point["avgscore"], 10);
		var reference_date = point["reference_date"];
		var dateInt = parseInt(reference_date);

		var newrange = []
		var newaverage = []
		// console.log("dateint: " + dateInt)
		// console.log("Start Time: "+ formattedStartDate)
		// console.log("End Time: "+ formattedEndDate)



		if (dateInt >= formattedStartDate && dateInt <= formattedEndDate){
			newrange.push(datetime, minscore, maxscore)
			newaverage.push(datetime, avgscore)
			ranges.push(newrange)
			averages.push(newaverage)
		}
	})
		// console.log("Ranges are: " + ranges)
		// console.log("Ranges are: " + ranges.length +" long")
		// console.log("Averages are: " + averages)
		// console.log("Averages are: " + averages.length +" long")



	$('#container-chart').highcharts({
        title: {
            text: 'Your Tweet Vibes'
        },

        chart: {
        	borderRadius: 20,
        	// plotBackgroundColor: "#BAB3B2"
        },

        credits: {
        	enabled: false
        },

        xAxis: {
            type: 'datetime'
        },

        yAxis: {
            title: {
                text: 'Sentiment'
            }
        },

        tooltip: {
            crosshairs: true,
            shared: true,
            valueSuffix: ''
        },

        series: [{
            name: 'Average',
            data: averages,
            zIndex: 1,
            marker: {
                fillColor: 'white',
                lineWidth: 2,
                lineColor: Highcharts.getOptions().colors[0]
            }
        }, {
            name: 'Range',
            data: ranges,
            type: 'arearange',
            color: "#66CD00",
            negativeColor: "#FF0000",
            lineWidth: 0,
            linkedTo: ':previous',
            fillOpacity: 0.3,
            zIndex: 0
        }]
    });
}

</script>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>